version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3356:3306
    volumes:
      - ./.database:/var/lib/mysql
    env_file:
      - ./env/mysql.env
